
safe: false

pygments: true
highlighter: rouge

baseurl: /
# github上请修改baseusl为http://nbguide.github.io
auto: false
destination: ./_site
title: 宁波向导软件开发

title1: 相关案例 
title2: 重要客户
title3: 合作伙伴
title4: 服务
title5: 关于我们

title8: 联系电话 
title9: 地址

name: 宁波海曙向导软件开发有限公司
address: 浙江宁波市海曙区马园路165号丰华名都3#1401
tel: 0574-87114234
site: https://nbguide.github.io

description: 专业的企业管理系统解决方案

servers:
    - name: servers1
      title: 网页适配
      description: 设计研发支持各类主流移动系统, <br /> 让用户实现在任何地点、时间都能进行业务处理。
      pic_url: images/branding.png

    - name: servers2
      title: 管理软件
      description: 为企业定制各类场合业务处理软件, <br /> 简易操作方便管理，满足不同业务的服务需求。
      pic_url: images/web.png

    - name: servers3
      title: 可定制
      description: 专为企业定制品牌特性量身定制直观的内容管理界面
      pic_url: images/print.png
